[package]
name = "pog3d"
version = "0.1.0"
authors = ["Michael Auderer <hermbit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"
rand = "0.8.3"
bitfont = "0.1.0"